---
language: node_js
sudo: false

node_js:
  - "5.9.1"

cache:
  directories:
    - node_modules
    - bower_components

install:
  - "npm install"
  - "bower install"

script:
  - npm test

notifications:
  email: false
